gauss/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('gentities.urls')),
    url(r'^', include('gprojects.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
]

gprojects/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from datetime import timedelta, datetime
from django.db.models import signals
from dateutil.rrule import rrule, MONTHLY, DAILY
# Create your models here.
import json

from gentities.models import Gentity, Guser
from gresources.models import Gresource
# from gcalendars.models import Gcalendar


class Gproject(models.Model):
    gentity = models.ForeignKey(Gentity, blank=True, null=True)
    name = models.CharField('Name of the project', blank=True, null=True, max_length=250)
    active = models.BooleanField('Is it active?', default=True)
    start_date = models.DateField('Starting date', blank=True, null=True)
    administrator = models.ForeignKey(Guser, blank=True, null=True)
    notes = models.TextField('Description of the project', blank=True, null=True)
    gresources = models.ManyToManyField(Gresource, blank=True)
    gusers_edit = models.ManyToManyField(Guser, blank=True, related_name='edit')
    removed = models.BooleanField('The project is removed', default=False)
    created = models.DateTimeField('Date of creation', auto_now_add=True)
    modified = models.DateTimeField('Last modification', auto_now=True)

    @property
    def end_date(self):
        return (datetime.today() + timedelta(days=10)).date()

    def can_guser_edit(self, guser):
        return True if (guser in self.gusers_edit.all() or guser == self.administrator) else False

    class Meta:
        ordering = ['active', 'created']

    def __unicode__(self):
        return u'%s (%s)' % (self.name, self.gentity.name)


########################################################################################

def update_active_baselines(sender, instance, created, **kwargs):
    if instance.active == True:
        baselines = Gbaseline.objects.filter(gproject=instance.gproject, active=True).exclude(id=instance.id)
        for baseline in baselines:
            baseline.active = False
            baseline.save()


class Gbaseline(models.Model):
    gproject = models.ForeignKey(Gproject, blank=True, null=True)
    name = models.CharField('Name', max_length=200, blank=True, null=True)
    start_date = models.DateTimeField('Starting date', blank=True, null=True)
    active = models.BooleanField('Is it the active one?', default=True)
    scale = models.IntegerField('Width in pixels for unit of time', blank=True, null=True, default=24)
    columns = models.IntegerField('Number of foundation columns occupied by the gantt chart', default=9)
    created = models.DateTimeField('Date of creation', auto_now_add=True)
    modified = models.DateTimeField('Last modification', auto_now=True)

    @property
    def jsonGtasks(self):
        def eval_col(t, col):
            if col == 'estimate_time_days':
                return t.estimate_time.seconds / 3600 / 24 + t.estimate_time.days
            elif col == 'ES':
                # return str(t.early_start)
                return t.pos
            elif col == 'LF':
                # return str(t.last_finish)
                return t.name
            else:
                return "error"

        tasks = self.gtask_set.all()
        gantt_tasks = []
        gcols = self.gcolumn_set.all()
        for t in tasks:
            cols = []
            # for gcol in gcols:
            # cols.append({'name': gcol.get_content_display(), 'pos': gcol.pos, 'value': getattr(t, gcol.content)})
            # cols.append({'name': gcol.get_content_display(), 'pos': gcol.pos, 'value': eval_col(t, gcol.content)})
            # gantt_tasks.append({'id': t.id, 'name': t.name, 'left': t.left, 'width': t.width, 'pos': t.pos,
            #                     'width_progress': t.width_progress, 'cols': cols})
            gantt_tasks.append({'id': t.id, 'name': t.name, 'left': t.left, 'width': t.width, 'pos': t.pos,
                                'width_progress': t.width_progress, 'es': str(t.es),
                                'duration': t.estimate_time_days, 'lf': str(t.lf)})
        return json.dumps(gantt_tasks)

    # @property
    # def jsonGtasks(self):
    #     def eval_col(t, col):
    #         if col == 'estimate_time_days':
    #             return t.estimate_time.seconds / 3600 / 24 + t.estimate_time.days
    #         elif col == 'ES':
    #             # return str(t.early_start)
    #             return t.pos
    #         elif col == 'LF':
    #             # return str(t.last_finish)
    #             return t.name
    #         else:
    #             return "error"
    #     tasks = self.gtask_set.all()
    #     gcols = self.gcolumn_set.all()
    #     gantt_tasks = {}
    #     cols = {}
    #     for t in tasks:
    #         cols.clear()
    #         for gcol in gcols:
    #             cols[gcol.id] = {'name': gcol.get_content_display(), 'pos': gcol.pos, 'value': eval_col(t, gcol.content)}
    #         gantt_tasks[t.id] = {'id': t.id, 'name': t.name, 'left': t.left, 'width': t.width, 'pos': t.pos,
    #                             'width_progress': t.width_progress, 'cols': cols}
    #     return json.dumps(gantt_tasks)

    @property
    def jsonGlinks(self):
        links = self.gtask_link_set.all()
        gantt_links = []
        for l in links:
            gantt_links.append(
                {'id': l.id, 'source': l.predecessor.id, 'target': l.successor.id, 'type': l.dependency})
        return json.dumps(gantt_links)

    @property
    def jsonGcolumns(self):
        gcols = self.gcolumn_set.all()
        gtasks = self.gtask_set.all()
        gantt_cols = []
        for t in gtasks:
            for gcol in gcols:
                gantt_cols.append({'gtask_id': t.id, 'name': gcol.get_content_display(), 'pos': gcol.pos,
                                   'value': str(getattr(t, gcol.content))})
        return json.dumps(gantt_cols)

    # @property
    # def start_date(self):
    #     return datetime.combine(self.gproject.start_date, datetime.min.time())

    @property
    def left_side(self):
        return 12 - self.columns

    @property
    def right_side(self):
        return self.columns

    # @property
    # def end_date(self):
    #     last_times = []
    #     last_tasks = Gtask.objects.filter(successors=None)
    #     for t in last_tasks:
    #         last_times.append(t.early_start + t.estimate_time)
    #     return max(last_times)

    @property
    def end_date(self):
        gtasks = Gtask.objects.filter(gbaseline=self)
        last_tasks = [gtask for gtask in gtasks if gtask.successors.count() == 0]
        last_times = [self.start_date]
        for t in last_tasks:
            last_times.append(t.early_start + t.estimate_time)
        return max(last_times)

    @property
    def project_duration(self):
        return self.end_date - self.start_date

    # @property
    # def month_list(self):
    #     diff_days = self.start_date.day - self.end_date.day
    #     end_date = self.end_date if diff_days < 0 else self.end_date + timedelta(diff_days)
    #     return rrule(MONTHLY, dtstart=self.start_date, until=end_date)

    @property
    def project_dates(self):
        current_month = self.start_date.month
        dates = [[]]
        n = 0
        for d in rrule(DAILY, dtstart=self.start_date, until=self.end_date):
            if current_month != d.month:
                current_month = d.month
                n += 1
                dates.append([])
            dates[n].append(d)
        return dates

    @property
    def project_num_days(self):
        return len(list(rrule(DAILY, dtstart=self.start_date, until=self.end_date)))

    @property
    def gtasks(self):
        return Gtask.objects.filter(gbaseline=self)

    # @property
    # def main_gtasks(self):
    #     return Gtask.objects.filter(gbaseline=self, gtask_parent=None)

    def __unicode__(self):
        return u'%s - %s (%s)' % (self.name, self.gproject, self.active)


signals.post_save.connect(update_active_baselines, sender=Gbaseline)

########################################################################################
# DIMENSIONS OF GANTT CHART BARS
########################################################################################

margin_task = 2
task_height = margin_task * 11
row_height = task_height + margin_task * 2


########################################################################################

class Gtask(models.Model):
    # As Soon As Possible, As Late As Possible, Starting Date, Ending Date, Start No Before that Date
    # Start No Later that Date, End No Before that Date, End No Later that Date
    TASK_RESTRICTIONS = (('ASAP', 'Lo antes posible'), ('ALAP', 'Lo más tarde posible'),
                         ('SD', 'Debe empezar el ...'), ('ED', 'Debe terminar el ...'),
                         ('SNBD', 'No iniciar antes del ...'), ('SNLD', 'Iniciar como muy tarde el ...'),
                         ('ENBD', 'No terminar antes del ...'), ('ENLD', 'Terminar como muy tarde el ...'))
    DISPLAY = (('none', 'none'), ('block', 'block'))
    gbaseline = models.ForeignKey(Gbaseline, blank=True, null=True)
    name = models.CharField('Name', max_length=200, blank=True, null=True)
    pos = models.IntegerField('Vertical position', blank=True, null=True)
    optimistic_time = models.DurationField('Optimistic time', blank=True, null=True, default=timedelta(days=1))
    likely_time = models.DurationField('Likely time', blank=True, null=True, default=timedelta(days=1))
    pessimistic_time = models.DurationField('Pessimistic time', blank=True, null=True, default=timedelta(days=1))
    gresources = models.ManyToManyField(Gresource, blank=True)
    priority = models.IntegerField('Priority', blank=True, null=True, default=500)
    restriction = models.CharField('Restriction type', choices=TASK_RESTRICTIONS, max_length=10, default='ASAP')
    restriction_date = models.DateTimeField('Restriction date', blank=True, null=True)

gprojects/templates/create_project.html
{% extends "base.html" %}
{#{% load my_templatetags %}#}

{% block contenido %}
    <h4 class="app_title">Datos del nuevo proyecto</h4>
    <form method="post" name="creategprojectform" id="creategprojectform">
        {% csrf_token %}
        <input type="hidden" name="action" id="action" value="create">
        <div class="row">
            <div class="columns large-8">
                <label>Nombre del proyecto:
                    {{ form.name }}
                </label>
            </div>
            <div class="columns large-4">
                <label>Administrador:
                    {{ form.administrator }}
                </label>
            </div>
        </div>
        <div class="row">
            <div class="columns large-12">
                <label>Anotaciones para este proyecto:
                    {{ form.notes }}
                </label>
            </div>
        </div>
    </form>
{% endblock %}




{% block final %}
    {#    <script src="/static/foundation-6/js/vendor/jquery.min.js"></script>#}
    {#<script src="/static/foundation-6/js/foundation.min.js"></script>#}
    {#<script src="/static/js/js.cookie.js"></script>#}
    <script>
    $('.check_button').click(function(e){
        e.preventDefault();
        $('#creategprojectform').submit();
    });
    </script>
{% endblock %}

gprojects/templates/gantt_gtask_data.html
{% load gproject_extras %}
<h4 class="app_title">Parámetros de la tarea</h4>
<input type="hidden" name="gtask_id" class="sending_predecessors" value="{{ gtask.id }}">
<input type="hidden" name="action" class="sending_predecessors" value="change_predecessors">

<ul class="tabs" data-tabs id="gtask-tabs">
    <li class="tabs-title is-active"><a href="#general_tab" aria-selected="true">General</a></li>
    <li class="tabs-title"><a href="#predecessors_tab">Predecessors</a></li>
    <li class="tabs-title"><a href="#hresources_tab">Human resources</a></li>
    <li class="tabs-title"><a href="#mresources_tab">Material resources</a></li>
    <li class="tabs-title"><a href="#constraints_tab">Constraints</a></li>
    <li class="tabs-title"><a href="#notes_tab">Notes</a></li>
</ul>

<div class="tabs-content" data-tabs-content="gtask-tabs">
    <div class="tabs-panel is-active" id="general_tab">
        <div class="row">
            <div class="columns large-9">
                <label>Nombre <span id="name-check" style="color:red;display: none;"><i class="fa fa-check"></i></span></label>
                <input type="text" name="name" id="name" value="{{ gtask.name }}" data-id="{{ gtask.id }}">
                </label>
            </div>
            <div class="columns large-3">
                <label> Duración estimada <span class="time-check" id="estimate-check" style="color:red;display: none;"><i
                        class="fa fa-check"></i></span></label>
                <input title="Duración estimada de  la tarea" type="text" name="estimate_time" id="estimate_time"
                       class="change_time"
                       value="{{ gtask.estimate_time|days }}d" data-id="{{ gtask.id }}" data-type="estimate">
                </label>
            </div>
        </div>
        <div class="row">
            <div class="columns large-4">
                <label>Duración optimista <span class="time-check" id="optimistic-check"
                                                style="color:red;display: none;"><i
                        class="fa fa-check"></i></span></label>
                <input title="Duración optimista de  la tarea" type="text" name="opmistic_time" id="optimistic_time"
                       class="change_time"
                       value="{{ gtask.optimistic_time|days }}d" data-id="{{ gtask.id }}" data-type="optimistic">
                </label>
            </div>
            <div class="columns large-4">
                <label>Duración probable <span class="time-check" id="likely-check" style="color:red;display: none;"><i
                        class="fa fa-check"></i></span></label>
                <input title="Duración pesimista de  la tarea" type="text" name="likely_time" id="likely_time"
                       class="change_time" value="{{ gtask.likely_time|days }}d" data-id="{{ gtask.id }}"
                       data-type="likely">
                </label>
            </div>
            <div class="columns large-4">
                <label>Duración pesimista <span class="time-check" id="pessimistic-check"
                                                style="color:red;display: none;"><i
                        class="fa fa-check"></i></span></label>
                <input title="Duración pesimista de  la tarea" type="text" name="pessimistic_time" id="pessimistic_time"
                       class="change_time"
                       value="{{ gtask.pessimistic_time|days }}d" data-id="{{ gtask.id }}" data-type="pessimistic">
                </label>
            </div>
        </div>
    </div>
    <div class="tabs-panel" id="predecessors_tab">
        <div class="row">
            <div class="columns large-12">
                <label>Predecesoras <span id="predecessors-check" style="color:red;display: none;"><i
                        class="fa fa-check"></i></span></label>
                <select class="predecessors sending_predecessors" id="id_predecessors" name="predecessors" multiple
                        data-id="{{ gtask.id }}">
                        {% for t in gtasks %}
                        <option value="{{ t.id }}" {% if t in gtask.predecessors.all %} selected {% endif %}>{{ t.name }}</option>
                    {% endfor %}
                </select>
                </label>
            </div>
        </div>
    </div>
    <div class="tabs-panel" id="hresources_tab">
        {#<div class="row">#}
        {#    <div class="columns large-12">#}
        {#        <label>Recursos#}
        {#            <select class="gresources" id="id_gresources" name="gresources" multiple>#}
        {#            </select>#}
        {#        </label>#}
        {#    </div>#}
        {#</div>#}
    </div>
    <div class="tabs-panel" id="mresources_tab">
        <p>hola3</p>
    </div>
    <div class="tabs-panel" id="constraints_tab">
        <p>hola4</p>
    </div>
    <div class="tabs-panel" id="notes_tab">
        <div class="row">
            <div class="columns large-12">
                <label>Observaciones
                    <textarea class="notes" id="id_notes" name="notes" rows="5"></textarea>
                </label>
            </div>
        </div>
    </div>
</div>


<button class="close-button" data-close aria-label="Close reveal" type="button">
    <span aria-hidden="true">&times;</span>
</button>


{#TASK_RESTRICTIONS = (('ASAP', 'Lo antes posible'), ('ALAP', 'Lo más tarde posible'),#}
{#                         ('SD', 'Debe empezar el ...'), ('ED', 'Debe terminar el ...'),#}
{#                         ('SNBD', 'No iniciar antes del ...'), ('SNLD', 'Iniciar como muy tarde el ...'),#}
{#                         ('ENBD', 'No terminar antes del ...'), ('ENLD', 'Terminar como muy tarde el ...'))#}
{#    DEPENDENCIES = (('FS', 'Finish to Start'), ('FF', 'Finish to Finish'),#}
{#                    ('SS', 'Start to Start'), ('SF', 'Start to Finish'),)#}
{#    gbaseline = models.ForeignKey(Gbaseline, blank=True, null=True)#}
{#    name = models.CharField('Name', max_length=200, blank=True, null=True)#}
{#    optimistic_time = models.DurationField('Optimistic time', blank=True, null=True, default=timedelta(days=1))#}
{#    likely_time = models.DurationField('Likely time', blank=True, null=True, default=timedelta(days=1))#}
{#    pessimistic_time = models.DurationField('Pessimistic time', blank=True, null=True, default=timedelta(days=1))#}
{#    gresources = models.ManyToManyField(Gresource, blank=True)#}
{#    priority = models.IntegerField('Priority', blank=True, null=True, default=500)#}
{#    restriction = models.CharField('Restriction type', choices=TASK_RESTRICTIONS, max_length=10)#}
{#    restriction_date = models.DateTimeField('Restriction date', blank=True, null=True)#}
{#    dependencies = models.CharField('Type of dependency', choices=DEPENDENCIES, max_length=10)#}
{#    percentage_complete = models.IntegerField('Percentage complete', blank=True, null=True, default=0)#}
{#    notes = models.TextField('Notes about the task', blank=True, null=True)#}
{#    created = models.DateTimeField('Date of creation', auto_now_add=True)#}
{#    modified = models.DateTimeField('Last modification', auto_now=True)#}
{#    children = models.ManyToManyField('self', blank=True, related_name='children')#}
{#    predecessors = models.ManyToManyField('self', blank=True, related_name='predecessors')#}
{#    successors = models.ManyToManyField('self', blank=True, related_name='successors')#}

gprojects/templates/gantt_schedule.html
{#{% load gproject_extras %}#}

<div class="columns small-{{ gbaseline.left_side }} left-pane">
    <div class="row" id="left-header" style="margin-left: 0px;">
        <div class="row" id="column_headers" style="margin-left:0;">
            <div class="gantt_list_column" style="width: 20px;border: none;text-align: center;">
                <i class="fa fa-check-square-o"></i>
            </div></div>
        <div class="row" style="margin-left: 0px;">&nbsp;</div>
    </div>

    <div class="row" id="task_list" style="margin-left: 0px;position:relative;white-space: nowrap;">
        <div id="task_list-1"></div>
    </div>

    <div class="row">
        <div class="columns small-12">
            <a class="button" id="add_gtask" data-id="{{ gbaseline.id }}"><i class="fa fa-plus"></i> Task</a>
        </div>
    </div>
</div>
<div class="columns small-{{ gbaseline.right_side }} right-pane">
    <div class="row" id="right-header" style="margin-left: 0px;">
        <div class="row" id="tl_months" style="margin-left: 0px;"></div>
        <div class="row" id="tl_days" style="margin-left: 0px;"></div>
    </div>

    <div class="row" id="task_bars" style="margin-left: 0px;position:relative;white-space: nowrap;">
        <div id="task_bars-1"></div>
    </div>
</div>

gprojects/templates/gantt_schedule_inicial.html
{% load gproject_extras %}
<div class="columns small-3 left-pane" style="overflow-x: auto;margin-top: -25px;">
    <div id="task_list">
        <div style="white-space: nowrap;border-bottom: 1px solid #eeeeee;height: 60px;"
             title="Work Breackdown Structure">
            WBS
        </div>
        {% for gtask in gbaseline.gtasks %}
            <div>
                <a class="gtask" id="name{{ gtask.id }}" data-id="{{ gtask.id }}">{{ gtask.name }}</a>
            </div>
        {% endfor %}
    </div>
    <div>
        <a class="button" id="add_gtask" data-id="{{ gbaseline.id }}"><i class="fa fa-plus"></i> Task</a>
    </div>
</div>
<div class="columns small-9 right-pane" style="overflow-x: auto;margin-top: -25px;">
    <div style="white-space: nowrap;height: 60px;width: {{ gbaseline.project_num_days|multiply:gbaseline.scale }}px;">
        {% for m in gbaseline.project_dates %}
            <div style="width:{{ m|length|multiply:gbaseline.scale }}px;float: left;text-align: center;">
                <div style="border-right: 1px solid #aaaaaa;">{{ m.0|date:"F Y" }}</div>
                {% for d in m %}
                    <div style="float: left;width: {{ gbaseline.scale }}px;border: 1px solid #eeeeee;">{{ d|date:'d' }}</div>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
    <div id="task_bars">
        {% for gtask in gbaseline.gtasks %}
            <div class="gtask_bar"
                 style="margin-left:{{ gtask.pixels.pxleft }}px;width: {{ gtask.pixels.pxdays }}px;">&nbsp;
                <div style="font-size:6pt;float: left;color:white;font-weight: 800;"> {{ gtask.tearly_date }}</div>
            </div>
        {% endfor %}
    </div>
</div>

gprojects/templates/gprojects.html
{% extends "base.html" %}
{#{% load my_templatetags %}#}

{% block contenido %}
    <style>
    .fa-lock{
        color:red;
    }
    </style>
    <h4 class="app_title">Gestión de los proyectos existentes</h4>
    <form method="post" name="gprojectsform" id="gprojectsform">
        {% csrf_token %}
        <input type="hidden" name="action" id="action" value="">
        <input type="hidden" name="gproject_selected" id="gproject_selected" value="">
        <div class="row">
            <div class="columns large-12">
                <ul class="accordion" data-accordion data-allow-all-closed="true">
                    {% for gproject in gprojects %}
                        <li class="accordion-item" data-accordion-item id="accordion{{ gproject.id }}">
                            <a href="#" class="accordion-title accordion_head"
                               data-id="{{ gproject.id }}"><i id="lock_{{ gproject.id }}"
                                   class="fa {% if gproject.active %}fa-unlock{% else %}fa-lock{% endif %}"></i>
                                &nbsp;&nbsp;&nbsp;<span id="gproject_name{{ gproject.id }}">{{ gproject.name }}</span>
                            </a>
                            <div class="accordion-content" data-tab-content id="accordion_content{{ gproject.id }}">
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

    </form>
{% endblock %}


{% block final %}
    <script>
        gp_buttons({plus: 'show'});

        $('.accordion_head').on('click', function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            $.post("/gprojects_ajax/", {action: 'project_data', 'id': id}, function (data) {
                $('#accordion_content' + id).html(data);
            });
        });

        $('.plus_button').on('click', function (e) {
            e.preventDefault();
            $('#action').val('create_project');
            $('#gprojectsform').submit();
        });

        $('body').on('change', '.switch-input', function (e) {
            var id = $(this).data('id');
            $.post("/gprojects_ajax/", {action: 'change_active', 'id': id}, function (data) {
                $('#lock_' + id).removeClass(data['remove']).addClass(data['add']);
                $('#accordion_content' + id).html(data['html']);
            }, 'json');
        });

        $('.accordion').on('click', '.remove_gproject', function (e) {
            var id = $(this).data('id');
            $.post("/gprojects_ajax/", {action: 'remove', 'id': id}, function (data) {
                $('#accordion' + id).hide();
            });
        });

    </script>
{% endblock %}

gprojects/templates/project_data.html
<div class="row">
    <div class="columns large-9">
        <div class="button-group">
            <a class="button project_button" data-id="{{ gproject.id }}"
               title="Elaborar el presupuesto de este proyecto"><i class="fa fa-paste"></i> Presupuesto</a>
            <a class="button project_button" data-action="charter" data-id="{{ gproject.id }}"
               title="Elaborar el 'project charter' del proyecto"><i class="fa fa-file-text"></i> Project charter</a>
            <a class="button" href="/gantt/{{ gproject.id }}/"
               title="Programación del proyecto a través del diagrama de Gantt"><i class="fa fa-tasks"></i> Gantt</a>
            <a class="button project_button" data-action="repository" data-id="{{ gproject.id }}"
               title="Ir al respositorio de documentos del proyecto"><i class="fa fa-folder-open"></i> Repositorio</a>
            <a class="button remove_gproject alert" data-action="remove" data-id="{{ gproject.id }}"
               title="Borrar el proyecto"><i class="fa fa-trash"></i> Borrar</a>
        </div>
    </div>
    <div class="columns large-3" style="position: relative;">
        <input title="Fecha de comienzo del proyecto" type="text" name="start_date" class="start_date"
               value="{{ gproject.start_date|date:'d-m-Y' }}" data-id="{{ gproject.id }}">
            <span id="date_check" style="color:red;display: none;position: absolute;right: 5px;top: -10px;"><i
                                    class="fa fa-check"></i></span>
    </div>

</div>
<div class="row">
    <div class="columns large-6">
        <label>Nombre del proyecto: <span id="name_check" style="color:red;display: none;"><i
                                    class="fa fa-check"></i></span>
            <input type="text" name="name" id="name{{ gproject.id }}" class="name_gproject" value="{{ gproject.name }}"
                   data-id="{{ gproject.id }}">
        </label>
    </div>
    <div class="columns large-4">
        <label>Administrador: <span id="administrator_check" style="color:red;display: none;"><i
                                    class="fa fa-check"></i></span>
            <select name="administrator" id="administrator{{ gproject.id }}" data-id="{{ gproject.id }}">
                <option value="{{ gproject.administrator.id }}">{{ gproject.administrator.last_name }}, {{ gproject.administrator.first_name }}</option>
            </select>
        </label>
    </div>
    <div class="columns large-2">
        <label>Realizándose:</label>
        <div class="switch active_switch" data-id="{{ gproject.id }}">
            <input class="switch-input" id="active{{ gproject.id }}" type="checkbox" data-id="{{ gproject.id }}"
                   {% if gproject.active %}checked{% endif %}>
            <label class="switch-paddle" for="active{{ gproject.id }}">
                <span class="show-for-sr">Proyecto en proceso de ejecución</span>
                <span class="switch-active" aria-hidden="true">Sí</span>
                <span class="switch-inactive" aria-hidden="true">No</span>
            </label>
        </div>
    </div>
</div>
<div class="row">
    <div class="columns large-12">
        <label>Anotaciones para este proyecto: <span id="notes_check" style="color:red;display: none;"><i
                                    class="fa fa-check"></i></span>
            <textarea data-id="{{ gproject.id }}" name="notes" id="notes{{ gproject.id }}" class="gproject_notes"
                      rows="10">{{ gproject.notes }}</textarea>
        </label>
    </div>
</div>

<script>
    $('.active_switch').foundation();

    $('.start_date').fdatepicker({
        language: 'es',
        format: 'dd-mm-yyyy',
        weekStart: 1
    });

    $('.start_date').change(function (e) {
        var id = $(this).data('id');
        var start_date = $(this).val();
        $.post("/gprojects_ajax/", {action: 'change_date', id: id, start_date: start_date}, function (data) {
            $('#date_check').show().delay(1500).fadeOut();
        });
    });

    $('body').on('propertychange input', '.gproject_notes', function (e) {
        var id = $(this).data('id');
        var notes = $(this).val();
        $.post("/gprojects_ajax/", {action: 'change_notes', id: id, notes: notes}, function (data) {
                $('#notes_check').show().delay(1500).fadeOut();
        });
    });

    $('body').on('propertychange input', '.name_gproject', function (e) {
        var id = $(this).data('id');
        var name = $(this).val();
        $.post("/gprojects_ajax/", {action: 'change_name', id: id, name: name}, function (data) {
            $('#gproject_name' + id).html(data);
            $('#name_check').show().delay(1500).fadeOut();
        });
    });

    $('body').on('change', '#administrator{{ gproject.id }}', function (e) {
        var id = $(this).data('id');
        var value = $(this).val();
        $.post("/gprojects_ajax/", {action: 'change_administrator', id: id, administrator: value}, function (data) {
            $('#administrator_check').show().delay(1500).fadeOut();
        });
    });

    $("#administrator{{ gproject.id }}").select2({
        theme: "foundation",
        placeholder: "Escribe parte del nombre",
        minimumInputLength: 3,
        ajax: {
            url: "/seek_users/",
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    q: params.term, // search term
                    page: params.page
                };
            },
            processResults: function (data) {
                return {
                    results: $.map(data, function (item) {
                        if (item.department) {
                            var department = ' (' + item.department + ')';
                        } else {
                            var department = '';
                        }
                        return {
                            text: item.last_name + ', ' + item.first_name + department,
                            id: item.id
                        }
                    })
                };
            }
        },
        templateResult: function (result) {
            return '<div class="select2-user-result">' + result.text + '</div>';
        },
        templateSelection: function (result) {
            return result.text;
        },
        escapeMarkup: function (markup) {
            return markup;
        }
    });
</script>