gauss/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('gentities.urls')),
    url(r'^', include('gprojects.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^captcha/', include('captcha.urls')),
]

gbudgets/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
import os

# Create your models here.

from gentities.models import Gentity, Guser


# Function to save files with a name that keeps consistency
def update_file(instance, filename):
    instance.file_name = filename
    ext = filename.partition('.')[2]
    now = datetime.now()
    new_filename = 'budget_file_%s.%s' % (now.strftime('%Y%m%d%H%M%f'), ext)
    return os.path.join("budgets/", new_filename)


class Budget_file(models.Model):
    file = models.FileField("File related to the budget", upload_to=update_file, blank=True)
    file_name = models.CharField('File name', max_length=200, blank=True, null=True)
    content_type = models.CharField("Type of file", max_length=200, blank=True, null=True)
    description = models.CharField("Small description", max_length=300, blank=True, null=True)

    def __unicode__(self):
        return u'%s' % (self.file)


class Gbudget(models.Model):
    gentity = models.ForeignKey(Gentity, blank=True, null=True)
    title = models.CharField('Title for the budget', blank=True, null=True, max_length=150)
    removed = models.BooleanField('The budget is removed?', default=False)
    administrator = models.ForeignKey(Guser, blank=True, null=True)
    gusers_edit = models.ManyToManyField(Guser, blank=True, related_name='can_edit_gbudget')
    initial_bc3 = models.ForeignKey(Budget_file, blank=True, null=True, related_name='initial')
    final_bc3 = models.ForeignKey(Budget_file, blank=True, null=True, related_name='final')
    notes = models.TextField('Description/Explanation of the budget', blank=True, null=True)
    created = models.DateTimeField('Created', auto_now_add=True)
    modified = models.DateTimeField('Last modification', auto_now=True)

    @property
    def root(self):
        return Crecord.objects.filter(gbudget=self, hierarchy=0)
    @property
    def chapters(self):
        return Crecord.objects.filter(gbudget=self, hierarchy=1)

    def __unicode__(self):
        return u'%s - %s (%s)' % (self.gentity, self.title, self.created)


class Vrecord(models.Model):
    """
    ~V | [ PROPIEDAD_ARCHIVO ] | VERSION_FORMATO [ \ DDMMAAAA ] | [ PROGRAMA_EMISION ] |
    [ CABECERA ] \ { ROTULO_IDENTIFICACION \ } | [ JUEGO_CARACTERES ] | [ COMENTARIO ] | [ TIPO INFORMACION ] |
    [ NUMERO CERTIFICACION  ] | [  FECHA CERTIFICACION ] | [ URL_BASE ] |
    """
    CHARSET = (('cp1252', 'ANSI'), ('850', '850'), ('cp437', '437'))
    TYPES = (
        (1, 'Base de datos'), (2, 'Presupuesto'), (3, 'Certificación (a origen)'),
        (4, u'Actualización de base de datos'))
    gbudget = models.ForeignKey(Gbudget)
    owner = models.CharField('Data base editor', blank=True, null=True, max_length=150)
    version = models.CharField('Format file version', default='FIEBDC-3/2016', max_length=100)
    date = models.DateField('Date', blank=True, null=True)
    emisor = models.CharField('Computer program or company that created the BC3 file', blank=True, null=True,
                              max_length=150)
    header = models.CharField('General title of ROTULOS_IDENTIFICACION', blank=True, null=True, max_length=200)
    char_set = models.CharField('Char set', choices=CHARSET, max_length=10, default='850')
    comment = models.CharField('Small description about this BC3', blank=True, null=True, max_length=300)
    type = models.IntegerField('Type of information', choices=TYPES, blank=True, null=True)
    # NÚMERO CERTIFICACIÓN: Valor numérico indicando el orden de la certificación (1, 2, 3,…)
    # Solo tiene sentido cuando el tipo de información es Certificación.
    certification_number = models.IntegerField('Order of the certification', blank=True, null=True)
    certification_date = models.DateField('Date of the certification', blank=True, null=True)
    url = models.URLField('Url where documents and images can be found', blank=True, null=True)

    class Meta:
        ordering = ['gbudget']

    def __unicode__(self):
        return u'%s (%s)' % (self.gbudget, self.date)


class Vrecord_label(models.Model):
    """
    ROTULO_IDENTIFICACION: Asigna secuencialmente títulos a los valores definidos en el campo PRECIO del registro ~C, y
    los conjuntos de campos de números de decimales del registro ~K, que tal como se indica en su ESPECIFICACION, puede
    representar distintas épocas, ámbitos geográficos, etc., estableciéndose una relación biunívoca entre ambos. Véanse
    los anexos 5 (Ámbitos territoriales) y 6 (Divisas).

    En el caso de que en el registro ~V existan más campos ROTULO_IDENTIFICACION que campos PRECIO en el registro ~C o
    que conjuntos de campos de decimales en el registro ~K, se entenderá que el PRECIO y los conjuntos de campos de
    decimales de dicho resto serán iguales al último definido.
    """
    vrecord = models.ForeignKey(Vrecord)
    title = models.CharField('Sequential title', max_length=200)

    class Meta:
        ordering = ['vrecord', 'id']

    def __unicode__(self):
        return u'%s (%s)' % (self.vrecord, self.title)


#############################################################

class Krecord(models.Model):
    """
    ~K | { DN \ DD \ DS \ DR \ DI \ DP \ DC \ DM \ DIVISA \ } | CI \ GG \ BI \ BAJA \ IVA |
    { DRC \ DC \ \ DFS \ DRS \ \ DUO \ DI \ DES \ DN \ DD \ DS \ DSP \ DEC \ DIVISA \ } | [ n ] |
    The first field only is there because compatibility. We will not read it.
    """
    gbudget = models.ForeignKey(Gbudget)
    ci = models.FloatField('Percentage CI', default=0)
    gg = models.FloatField('Percentage GG', default=13)
    bi = models.FloatField('Percentage BI', default=6)
    baja = models.FloatField('Percentage BAJA', default=1)
    iva = models.FloatField('Percentage IVA', default=21)

    @property
    def scopes(self):
        return Krecord_scope.objects.filter(krecord=self)

    class Meta:
        ordering = ['gbudget']

    def __unicode__(self):
        return u'%s (CI %s, GG %s, BI %s, BAJA %s, IVA %s)' % (
            self.gbudget, self.ci, self.gg, self.bi, self.baja, self.iva)


class Krecord_scope(models.Model):
    krecord = models.ForeignKey(Krecord, related_name='additional')
    vrecord_label = models.ForeignKey(Vrecord_label, related_name='krecord_scope')
    # Number of decimal places of the ...
    drc = models.IntegerField('... efficiency (or measure) in a chapter or subchapter break down.', default=3)
    dc = models.IntegerField('... price of a chapter or subchapter.', default=2)
    dfs = models.IntegerField('... factores de rendimiento de unidades de obra y de elementos compuestos.', default=3)
    drs = models.IntegerField('... rendimientos de las unidades de obra y de los elementos compuestos.', default=3)
    duo = models.IntegerField('... price of a unit of work.', default=2)
    di = models.IntegerField('... importes resultantes de multiplicar los rendimientos totales de los ...', default=2)
    des = models.IntegerField('... price of the simple elements.', default=2)
    dn = models.IntegerField('... field "equal-size parts" in the measure lines.', default=2)
    dd = models.IntegerField('... three dimensions in the measure lines.', default=2)
    ds = models.IntegerField('... total sum of a measure.', default=2)
    dsp = models.IntegerField('... línea de subtotal de mediciones.', default=2)
    dec = models.IntegerField('... importe de los elementos compuestos.', default=2)
    divisa = models.CharField('... monetary unit.', default='Euro', max_length=10)

    class Meta:
        ordering = ['krecord__gbudget']

    def __unicode__(self):
        return u'%s (DRC %s, DC %s, DFS %s, DRS %s, DUO %s, DI %s, DES %s, DN %s, ...)' % (
            self.krecord, self.drc, self.dc, self.dfs, self.drs, self.duo, self.di, self.des, self.dn)


#############################################################

class Crecord(models.Model):
    """
    ~C | CODIGO { \ CODIGO } | [ UNIDAD ] | [ RESUMEN ] | { PRECIO \ } | { FECHA \ } | [ TIPO ] |
    """
    TYPES = ((0, 'Sin clasificar'), (1, 'Mano de obra'), (2, 'Maquinaria y medios auxiliares'), (3, 'Materiales'),
             (4, 'Componentes adicionales de residuo'), (5, 'Clasificación de residuo'))
    HIERARCHY = ((0, 'Root'), (1, 'Chapter'), (2, 'Normal concept'))
    gbudget = models.ForeignKey(Gbudget)
    code = models.CharField('Code of the described concept', max_length=22)
    hierarchy = models.IntegerField('Hierarchy: root, chapter or concept', choices=HIERARCHY, default=2)
    unit = models.CharField('Unit of measurement', blank=True, null=True, max_length=7)
    summary = models.CharField('Summary of the concept', blank=True, null=True, max_length=300)
    type = models.CharField('Type of concept', blank=True, null=True, max_length=10)
    # ~T | CODIGO_CONCEPTO |  TEXTO_DESCRIPTIVO  |
    text = models.TextField('Concept description', blank=True, null=True)

    @property
    def children(self):
        return Drecord.objects.filter(parent=self).order_by('child__code')

    def __unicode__(self):
        if self.summary:
            if len(self.summary) > 50:
                s = '%s...' % self.summary[:50]
            else:
                s = '%s' % self.summary
        else:
            s = 'No summary'
        return u'Budget: %s, %s - (%s) %s' % (self.gbudget.id, self.code, self.get_hierarchy_display(), s)
        #
        # return '%s %s %s' % (self.gbudget.id, self.code, s)


class Crecord_alias(models.Model):
    crecord = models.ForeignKey(Crecord)
    code = models.CharField('Alias code for crecord.code', max_length=22)

    def __unicode__(self):
        return u'Budget: %s, Alias: %s -> Real code: %s' % (self.crecord.gbudget.id, self.code, self.crecord.code)


class Crecord_price(models.Model):
    crecord = models.ForeignKey(Crecord)
    vrecord_label = models.ForeignKey(Vrecord_label, related_name='crecord_price')
    price = models.FloatField('Price of the concept', blank=True, null=True)

gmessages/models.py
# -*- coding: utf-8 -*-
from django.db import models
from gentities.models import Guser, Gentity
from datetime import datetime
import os

# Las siguientes líneas son para eliminar las etiquetas html (html tags) del mensaje:
from HTMLParser import HTMLParser


class MLStripper(HTMLParser):
    def __init__(self):
        self.reset()
        self.fed = []

    def handle_data(self, d):
        self.fed.append(d)

    def get_data(self):
        return ' '.join(self.fed)


def strip_tags(html):
    s = MLStripper()
    s.feed(html)
    return s.get_data()


# Manejo de los ficheros subidos para que se almacenen con el nombre que deseo y no con el que originalmente tenían
def update_fichero(instance, filename):
    nombre = filename.partition('.')
    ahora = datetime.now()
    fichero = str(instance.propietario.id) + '_' + nombre[0].replace(' ', '_') + '_' + str(ahora.day) + '-' + str(
        ahora.month) + '-' + str(ahora.year) + '.' + nombre[2]
    return os.path.join("adjuntos/", fichero)


class Adjunto(models.Model):
    propietario = models.ForeignKey(Guser)
    fichero = models.FileField("Fichero con información", upload_to=update_fichero, blank=True)
    content_type = models.CharField("Tipo de archivo", max_length=200, blank=True, null=True)

    class Meta:
        app_label = 'mensajes'

    def filename(self):
        f = os.path.basename(self.fichero.name)
        return os.path.split(f)[1]

    def __unicode__(self):
        return u'%s (%s)' % (self.fichero, self.propietario.gauser.get_full_name())


class Etiqueta(models.Model):
    propietario = models.ForeignKey(Guser)
    nombre = models.CharField("Etiqueta", max_length=500)

    class Meta:
        app_label = 'mensajes'

    def __unicode__(self):
        return u'%s (%s)' % (self.nombre, self.propietario.gauser.get_full_name())


class Mensaje(models.Model):
    emisor = models.ForeignKey(Guser, related_name="emisor")
    receptores = models.ManyToManyField(Guser, related_name="receptores")
    adjuntos = models.ManyToManyField(Adjunto, related_name="adjuntos", blank=True)
    etiquetas = models.ManyToManyField(Etiqueta, related_name="etiquetas", blank=True)
    fecha = models.DateTimeField("Fecha y hora de envío")
    asunto = models.CharField("Asunto", max_length=500, null=True, blank=True)
    mensaje = models.TextField("Texto del Mensaje (html)")
    mensaje_texto = models.TextField("Texto del mensaje (plain/text)", null=True, blank=True)
    tipo = models.CharField("Tipo", max_length=30, null=True, blank=True)

    class Meta:
        app_label = 'mensajes'

    def men_ini(self):  #Devuelve los primeros caracteres del mensaje
        ncar = 85
        sin_tags = strip_tags(self.mensaje)
        if len(sin_tags) > 85:
            return sin_tags[:ncar] + '...'
        else:
            return sin_tags

    def __unicode__(self):
        return u'Enviado por %s (%s) - %s' % (self.emisor.gauser.get_full_name(), self.fecha, self.asunto)


class Borrado(models.Model):
    eraser = models.ForeignKey(Guser)
    mensaje = models.ForeignKey(Mensaje, related_name="mensaje_borrado")

    class Meta:
        app_label = 'mensajes'

    def __unicode__(self):
        return u'Borrado por %s (%s) - %s' % (
        self.eraser.gauser.get_full_name(), self.mensaje.fecha, self.mensaje.asunto)


class Leido(models.Model):
    lector = models.ForeignKey(Guser)
    mensaje = models.ForeignKey(Mensaje, related_name="mensaje_leido")

    class Meta:
        app_label = 'mensajes'

    def __unicode__(self):
        return u'Leído por %s (%s) - %s' % (self.lector.gauser.get_full_name(), self.mensaje.fecha, self.mensaje.asunto)


class Importante(models.Model):
    marcador = models.ForeignKey(Guser)
    mensaje = models.ForeignKey(Mensaje, related_name="mensaje_importante")

    class Meta:
        app_label = 'mensajes'

    def __unicode__(self):
        return u'Marcado como importante por %s (%s) - %s' % (
        self.marcador.gauser.get_full_name(), self.mensaje.fecha, self.mensaje.asunto)


class Aviso(models.Model):
    usuario = models.ForeignKey(Guser)
    aviso = models.TextField("Mensaje de aviso")
    ip = models.CharField("Dirección IP en la que estaba el usuario", max_length=50, null=True, blank=True)
    link = models.CharField("Redireccionamiento", max_length=100, null=True, blank=True)
    fecha = models.DateTimeField("Fecha y hora en la que se generó el aviso")
    aceptado = models.BooleanField("¿Ha sido aceptado/OK?", default=False)

    class Meta:
        app_label = 'mensajes'

    def __unicode__(self):
        return u'%s (%s)--%s' % (self.aviso, self.fecha, self.usuario)


class Mensaje_cola(models.Model):
    mensaje = models.ForeignKey(Mensaje, blank=True, null=True)
    receptores = models.TextField("Direcciones de correo separadas por un punto y coma")
    enviado = models.BooleanField("El mensaje ha sido enviado?", default=False)
    ultima_parte = models.BooleanField("Última parte del mensaje encolado?", default=False)
    creado = models.DateTimeField("Fecha y hora de encolar el mensaje", auto_now_add=True)
    modificado = models.DateTimeField("Fecha y hora en la que se envió efectivamente el correo", auto_now=True)
    class Meta:
        ordering = ['creado', 'id']
        app_label = 'mensajes'
    def __unicode__(self):
        return u'%s (%s - %s)' % (self.mensaje.asunto, self.creado, self.modificado)

gmessages/templates/avisos.html
{% for aviso in avisos %}
    <p> {% autoescape off %} {{ aviso.aviso }} {% endautoescape %} </p>
{% endfor %}

gmessages/templates/correo.html
{% extends "base.html" %}
{% load my_templatetags %}

{% block contenido %}
    <form action="" method="post" enctype="multipart/form-data" id="{{ formname }}" name="{{ formname }}">
        {% csrf_token %}
        <input type="hidden" name="action" id="action" value="">
        <input type="hidden" name="tipo_respuesta" id="tipo_respuesta" value="{{ tipo_respuesta }}">
        <input type="hidden" name="adjuntos_reenviados" id="adjuntos_reenviados"
               value="{% for adjunto in adjuntos %}{{ adjunto.id }},{% endfor %}">
        <input type="hidden" name="usa_mensaje" value="{{ usa_mensaje }}">

        <div>
            <h4 style="text-align: center;color: #008CBA;"><strong>Envío de correos/mensajes</strong></h4>
        </div>
        <div class="row">
            <div class="columns large-12">
                <label>Selecciona receptores
                    <div class="button-bar">
                        {% for sub_accesible in sub_accesibles %}
                            {% if sub_accesible.mensajes %}
                                <ul class="button-group">
                                    <li>
                                        <a title="Pincha aquí para seleccionar a todos los miembros de {{ sub_accesible.nombre }}"
                                           id="socios___{{ sub_accesible.id }}" href="#"
                                           class="buscar_receptores_subentidad small button">{{ sub_accesible.nombre }}</a>
                                    </li>
                                    <li><a id="borrar_socios___{{ sub_accesible.id }}" href="#"
                                           class="alert borrar_receptores_subentidad small button alert"
                                           title="Pincha aquí para borrar los miembros de {{ sub_accesible.nombre }}">
                                        <i class="fa fa-times"></i></a>
                                    </li>
                                </ul>
                            {% endif %}
                            {% if sub_accesible.edad_max < 19 %}
                                <ul class="button-group">
                                    <li>
                                        <a title="Pincha aquí para seleccionar a todos los padres de {{ sub_accesible.nombre }}"
                                           id="padres___{{ sub_accesible.id }}" href="#"
                                           class="buscar_receptores_subentidad small button">{{ sub_accesible.nombre }}(madres/padres)</a>
                                    </li>
                                    <li><a id="borrar_padres___{{ sub_accesible.id }}" href="#"
                                           class="alert borrar_receptores_subentidad small button alert"
                                           title="Pincha aquí para borrar los miembros de {{ sub_accesible.nombre }}">
                                        <i class="fa fa-times"></i></a>
                                    </li>
                                </ul>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <input type="hidden" name="mensaje-receptores" id="id_receptores" value="">
                </label>
            </div>
        </div>

        <div class="row">
            <div class="columns large-12">
                <label>Direcciones de otros receptores:
                    <input type="text" id="receptores_manuales" name="receptores_manuales" value="">
                </label>
            </div>
        </div>

        <div class="row">
            <div class="columns large-12">
                <label>Asunto
                    {{ form1.asunto }}
                </label>
            </div>
        </div>

        <div class="row">
            <div class="columns large-12" id="adjuntos_div">
            </div>
        </div>
        {% if tipo_respuesta == 'reenviar' %}
            <div class="row">
                <div class="columns large-12" style="padding: 10px;margin-left: 20px;">
                    {% for adjunto in adjuntos %}
                        <span id="nombre_adjunto_{{ adjunto.id }}">
                    <a><i id="reenviar_adjunto___{{ adjunto.id }}" class="fa fa-remove adjuntos_reenviar"></i></a>
                        {{ adjunto.filename }}{% if not forloop.last %}, {% endif %}
                    </span>
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        <div class="row">
            <div class="columns large-12">
                <label>Redacta el mensaje
                    {{ form1.mensaje }}
                </label>
            </div>
        </div>
    </form>


{% endblock %}

{% block final %}
    <script src="/static/gauss_fileupload/gauss_FileUpload.js"></script>
    <script>
        $("#id_receptores").select2({
            placeholder: "Escribe parte del nombre",
            minimumInputLength: 3,
            multiple: true,
            ajax: {
                url: "/ajax_mensajes/",
                dataType: 'json',
                quietMillis: 100,
                data: function (term, page) { // page is the one-based page number tracked by Select2
                    return {
                        action: 'receptores',
                        q: term, //search term
                        page_limit: 10, // page size
                        page: page // page number
                    };
                },
                results: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {
                                text: item.text,
                                id: item.id
                            }
                        })
                    };
                }
            },
            formatResult: function (resultado) {
                return '<div class="select2-user-result">' + resultado.text + '</div>';
            },
            formatSelection: function (resultado) {
                $('#gauser_extra_selected').val(resultado.id);
                return resultado.text;
            },
            dropdownCssClass: "bigdrop", // apply css that makes the dropdown taller
            escapeMarkup: function (m) {
                return m;
            } // we do not want to escape markup since we are displaying html in results
        });


        $(".buscar_receptores_subentidad").click(function (e) {
            e.preventDefault();
            var existentes = $("#id_receptores").select2("data");
            $.post("/ajax_mensajes/", {subentidad: $(this).attr('id'), action: 'receptores_subentidad'  },
                    function (data) {
                        $("#id_receptores").select2("data", data.concat(existentes));
                    },
                    'json');
        });

        $(".borrar_receptores_subentidad").click(function (e) {
            e.preventDefault();
            var existentes = $("#id_receptores").select2("data");
            var id = $(this).attr('id').split('___');
            if (id[0] == 'borrar_socios') {
                var id = 'socios___' + id[1];
            } else {
                var id = 'padres___' + id[1];
            }
            $.post("/ajax_mensajes/", {subentidad: id, action: 'receptores_subentidad'  },
                    function (data) {
                        var diff = existentes.filter(function (current) {
                            return data.filter(function (current_b) {
                                return current_b.id == current.id && current_b.text == current.text
                            }).length == 0
                        });

                        $("#id_receptores").select2("data", diff);
                    },
                    'json');
        });


        habilita(['s_envelope-o', 's_send-o']);

        $('#adjuntos_div').gaussFileUpload({
            tag_a: '<i class="fa fa-paperclip"></i> Pulsa aquí para adjuntar archivos al correo'});

        $('#Contenido').on('click', '#attach_file', function () {
            $('#adjuntos_div').show();
            $('#id_file').click();
            setTimeout(function () {
                $('#id_file').val($('#id_file').val());
            }, 1);
        });

        $('.adjuntos_reenviar').click(function (e) {
            e.preventDefault();
            var id = $(this).attr('id').split('___')[1];
            $('#nombre_adjunto_' + id).hide();
            var vec_list = $('#adjuntos_reenviados').val().split(',')
            var index = vec_list.indexOf(id);
            if (index > -1) {
                vec_list.splice(index, 1);
            }
            $('#adjuntos_reenviados').val(vec_list.join());
        });

        {#        $("#id_receptores").select2({placeholder: "Escribe parte del nombre para buscar coincidencias"});#}

        {#        $('.subentidad_convocada').click(function () {#}
        {#            var id_subentidad_selected = $(this).attr('id').split('___')[1];#}
        {#            if ($('#hidden___' + id_subentidad_selected).val() == 0) {#}
        {#                $('.socio.sub___' + id_subentidad_selected).prop('selected', true);#}
        {#                $('#hidden___' + id_subentidad_selected).val(1);#}
        {#                $('#id_receptores').trigger('change');#}
        {#            } else {#}
        {#                $('.socio.sub___' + id_subentidad_selected).prop('selected', false);#}
        {#                $('#hidden___' + id_subentidad_selected).val(0);#}
        {#                $('#id_receptores').trigger('change');#}
        {#            }#}
        {#        });#}
        {##}
        {#        $('.padres_subentidad_convocada').click(function () {#}
        {#            var id_subentidad_selected = $(this).attr('id').split('___')[1];#}
        {#            if ($('#padreshidden___' + id_subentidad_selected).val() == 0) {#}
        {#                $('.padre.sub___' + id_subentidad_selected).prop('selected', true);#}
        {#                $('#padreshidden___' + id_subentidad_selected).val(1);#}
        {#                $('#id_receptores').trigger('change');#}
        {#            } else {#}
        {#                $('.padre.sub___' + id_subentidad_selected).prop('selected', false);#}
        {#                $('#padreshidden___' + id_subentidad_selected).val(0);#}
        {#                $('#id_receptores').trigger('change');#}
        {#            }#}
        {#        })#}


        $("#envelope-o_sign").click(function (e) {
            e.preventDefault();
            $('#action').val('mail');
            document.{{formname}}.submit();
        });

        $("#send-o_sign").click(function (e) {
            e.preventDefault();
            $('#action').val('telegram');
            $('#telegram').val()
            document.{{formname}}.submit();
        });


        editor = wysihtmleditor('id_mensaje-mensaje', {attach: false});

        {% if receptores %}
            $("#id_receptores").select2("data", {% autoescape off %}{{receptores}} {% endautoescape %});
            $('#id_mensaje-mensaje').focus();
            $('#id_mensaje-mensaje')[0].selectionStart = 0;
            {#$('#id_mensaje-mensaje').selectionEnd = 0;#}
            {#        editor.focus();#}
        {% endif %}

    </script>

{% endblock %}

gmessages/templates/mensajes2pdf.html
{% load my_templatetags %}
<h2 style="text-align:center;"> Mensajes/Correos ({{ mensajes.0.emisor.entidad.name }})</h2>
<strong> {% now "j \d\e F \d\e Y" %}</strong>
<br>
<hr>
<br>
{% for mensaje in mensajes %}
    <strong>Emisor:</strong> {{ mensaje.emisor.gauser.get_full_name }}, <strong>Fecha:</strong> {{ mensaje.fecha|date:"j \d\e F \d\e Y" }}<br>
    <strong>Asunto:</strong> {% autoescape off %} {{ mensaje.asunto }} {% endautoescape %}<br>
    <strong>Receptores: </strong> {% for receptor in mensaje.receptores.all %} {{ receptor.get_full_name }}, {% endfor %}
    <br><br>
    {% autoescape off %} {{ mensaje.mensaje }} {% endautoescape %}
    <hr style="color: gray;">
{% endfor %}

gmessages/templates/pagination_gauss.html
{% if pagination|length > 1 %}
    <ul class="pagination" role="menubar" aria-label="Pagination">
        <li class="arrow pagina_anterior_gauss"><a href="">&laquo; Anterior</a></li>
        {% for page in pagination %}
            <li class="{{ page.current }} paginas_gauss {% if forloop.last %}ultima{% endif %}" id="page___{{ forloop.counter }}"><a href="">
                {{ page.first }}{% if page.last %}-{{ page.last }}{% endif %}</a></li>
        {% endfor %}
        <li class="arrow pagina_siguiente_gauss"><a href="">Siguiente &raquo;</a></li>
    </ul>
{% endif %}

gmessages/templates/responder_mensaje.html
<link rel="stylesheet" type="text/css" href="/static/js/CLEditor1_4_3/jquery.cleditor.css" />
<script type="text/javascript" src="/static/js/CLEditor1_4_3/jquery.cleditor.min.js"></script>
<script src="/static/js/jquery.MultiFile.js"></script>

<div style="padding-bottom:10px;clear:left;">
  <div style="padding:20px;" id="adjuntos_div">
    <i style="font-size:11pt;" class="fa fa-paperclip"></i>Adjuntar archivos:<input class="multi" type="file" name="files">
  </div>

  <div style="padding:20px;clear:left;" id="django_form">
   Redacta el mensaje:
    <br/>
    <textarea id="id_mensaje" name="mensaje"></textarea>
  </div>
</div>

<script>
  $("#id_mensaje").cleditor({
      width:        'auto', // width not including margins, borders or padding
      height:       250, // height not including margins, borders or padding
      controls:     // controls to add to the toolbar
		    "bold italic underline strikethrough subscript superscript | size " +
		    "style | bullets numbering | " +
		    "alignleft center alignright justify | undo redo | " +
		    "rule image link unlink",
      });
</script>